version: .{build}-{branch}
image: Visual Studio 2019

cache:
 - '%LOCALAPPDATA%\pip\Cache'

environment:

  SYSTEMROOT: "C:\\WINDOWS"

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"

install:
  - "set PATH=%PYTHON%\\Scripts;%PATH%"
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools^>=20.3 wheel"
  - "%PYTHON%\\python.exe -m pip install -U -rtest-requirements.txt codecov"
  - "%PYTHON%\\python.exe -m pip install -rrequirements.txt"

build_script:
  - "%PYTHON%\\python.exe -m pip install -e ."

test_script:
  - |
    %PYTHON%\\python.exe -m pytest --cov --cov-config=.coveragerc --cov-report= -n auto --strict-markers -p no:cacheprovider -p no:stepwise --junit-xml=tests.xml
  - "%PYTHON%\\python.exe -m coverage report"
  - "%PYTHON%\\python.exe -m coverage xml"
  - "%PYTHON%\\python.exe -m codecov --file coverage.xml"

on_finish:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($Env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))

branches:
  only:
    - main
